export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_COUNTRY = "GET_COUNTRY";
export const GET_COUNTRY_BY_NAME = "GET_COUNTRY_BY_NAME";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const ORDER = "ORDER";
export const FILTER_CONTINENT = "FILTER_CONTINENT"; 
export const FILTER_BY_ACTIVITY = "FILTER_BY_ACTIVITY";
export const PAGINATED = "PAGINATED";
